import 'carModels.dart';

List<CarModel> carModels = [
  // Previous BMW
  CarModel(
    brand: "BMW",
    model: "X5",
    version: "M Sport",
    year: DateTime(2023, 5, 20),
    cylinders: 6,
    fuel: "Gasoline",
    gearbox: "Automatic",
    drive: "AWD",
    bodyType: "SUV",
    condition: "New",
    titleStatus: "Clean",
    paintColor: "Black",
    options: ["Panoramic Roof", "Heads-up Display", "Harman Kardon Sound System"],
  ),
  // New BMW
  CarModel(
    brand: "BMW",
    model: "3 Series",
    version: "330i",
    year: DateTime(2023, 8, 12),
    cylinders: 4,
    fuel: "Gasoline",
    gearbox: "Automatic",
    drive: "RWD",
    bodyType: "Sedan",
    condition: "New",
    titleStatus: "Clean",
    paintColor: "Silver",
    options: ["Sunroof", "Leather Seats", "Navigation System"],
  ),
  CarModel(
    brand: "BMW",
    model: "X5",
    version: "M Sport",
    year: DateTime(2023, 7, 15),
    cylinders: 8,
    fuel: "Gasoline",
    gearbox: "Manual",
    drive: "RWD",
    bodyType: "Crossover",
    condition: "New",
    titleStatus: "Clean",
    paintColor: "White",
    options: ["Sunroof", "Leather Seats", "Navigation System"],
  ),
  // Previous Audi
  CarModel(
    brand: "Audi",
    model: "A4",
    version: "Premium Plus",
    year: DateTime(2022, 9, 10),
    cylinders: 4,
    fuel: "Gasoline",
    gearbox: "Automatic",
    drive: "AWD",
    bodyType: "Sedan",
    condition: "Used",
    titleStatus: "Clean",
    paintColor: "White",
    options: ["Virtual Cockpit", "Bang & Olufsen Sound System"],
  ),
  // New Audi
  CarModel(
    brand: "Audi",
    model: "Q7",
    version: "Premium",
    year: DateTime(2023, 11, 25),
    cylinders: 6,
    fuel: "Gasoline",
    gearbox: "Automatic",
    drive: "AWD",
    bodyType: "SUV",
    condition: "New",
    titleStatus: "Clean",
    paintColor: "Blue",
    options: ["Panoramic Sunroof", "Premium Audio System"],
  ),
  CarModel(
    brand: "Audi",
    model: "A4",
    version: "Premium Plus",
    year: DateTime(2023, 10, 5),
    cylinders: 4,
    fuel: "Gasoline",
    gearbox: "Manual",
    drive: "FWD",
    bodyType: "Hatchback",
    condition: "Used",
    titleStatus: "Clean",
    paintColor: "Red",
    options: ["Panoramic Sunroof", "Premium Audio System"],
  ),
  CarModel(
    brand: "BMW",
    model: "X5",
    version: "M Sport",
    year: DateTime(2023, 5, 20),
    cylinders: 6,
    fuel: "Gasoline",
    gearbox: "Automatic",
    drive: "AWD",
    bodyType: "SUV",
    condition: "New",
    titleStatus: "Clean",
    paintColor: "Black",
    options: ["Panoramic Roof", "Heads-up Display", "Harman Kardon Sound System"],
  ),
  CarModel(
    brand: "Audi",
    model: "A4",
    version: "Premium Plus",
    year: DateTime(2022, 9, 10),
    cylinders: 4,
    fuel: "Gasoline",
    gearbox: "Automatic",
    drive: "AWD",
    bodyType: "Sedan",
    condition: "Used",
    titleStatus: "Clean",
    paintColor: "White",
    options: ["Virtual Cockpit", "Bang & Olufsen Sound System"],
  ),
  CarModel(
    brand: "Toyota",
    model: "Camry",
    version: "V6 LE",
    year: DateTime(2022, 1, 15),
    cylinders: 6,
    fuel: "Gasoline",
    gearbox: "Automatic",
    drive: "FWD",
    bodyType: "Sedan",
    condition: "Used",
    titleStatus: "Clean",
    paintColor: "Silver",
    options: ["Sunroof", "Leather Seats", "Navigation System"],
  ),
  CarModel(
    brand: "Tesla",
    model: "Model S",
    version: "Plaid",
    year: DateTime(2023, 12, 1),
    cylinders: 0, // Electric cars don't have cylinders
    fuel: "Electric",
    gearbox: "Automatic",
    drive: "AWD",
    bodyType: "Sedan",
    condition: "New",
    titleStatus: "Clean",
    paintColor: "Red",
    options: ["Autopilot", "Full Self-Driving", "Performance Upgrade"],
  ),
  CarModel(
    brand: "Lamborghini",
    model: "Aventador",
    version: "SVJ",
    year: DateTime(2023, 6, 15),
    cylinders: 12,
    fuel: "Gasoline",
    gearbox: "Automatic",
    drive: "AWD",
    bodyType: "Supercar",
    condition: "New",
    titleStatus: "Clean",
    paintColor: "Yellow",
    options: ["Carbon Fiber Exterior Package", "Lamborghini Telemetry"],
  ),
  CarModel(
    brand: "Porsche",
    model: "911",
    version: "Turbo S",
    year: DateTime(2023, 10, 5),
    cylinders: 6,
    fuel: "Gasoline",
    gearbox: "Automatic",
    drive: "RWD",
    bodyType: "Coupe",
    condition: "New",
    titleStatus: "Clean",
    paintColor: "Blue",
    options: ["Porsche Ceramic Composite Brakes", "Sport Chrono Package"],
  ),
  CarModel(
    brand: "Ferrari",
    model: "488",
    version: "Pista",
    year: DateTime(2023, 7, 20),
    cylinders: 8,
    fuel: "Gasoline",
    gearbox: "Automatic",
    drive: "RWD",
    bodyType: "Sports Car",
    condition: "New",
    titleStatus: "Clean",
    paintColor: "Black",
    options: ["Carbon Fiber Exterior", "Ferrari Track Experience"],
  ),
  CarModel(
    brand: "Maserati",
    model: "Levante",
    version: "Trofeo",
    year: DateTime(2023, 9, 8),
    cylinders: 8,
    fuel: "Gasoline",
    gearbox: "Automatic",
    drive: "AWD",
    bodyType: "SUV",
    condition: "New",
    titleStatus: "Clean",
    paintColor: "Silver",
    options: ["Bowers & Wilkins Premium Sound System", "Advanced Driver Assistance"],
  ),
];
